name: bui_smart_campus
description: BUI Smart Campus - Flutter Final Project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  pdf: ^3.8.4
  printing: ^5.11.0
  path_provider: ^2.1.0
  share_plus: ^7.0.0
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true